services: 
    mongo: 
      image: mongo:latest
      container_name: mongo 
      ports: 
        - "7000:27017"
      volumes:
        - tracker-data:/data/db
        
    server: 
      build: . 
      container_name: tracker
      ports: 
        - "3000:3000"
      depends_on: 
        - mongo
      environment: 
        - MONGO_URI=mongodb://mongo:27017/tracker
      volumes: 
        - ./:/app

volumes: 
  tracker-data: